[build]
  publish = "."
  
[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/usai-general-services-administration-artificial-intelligence-google-meta-anthropic-claude/"
  to = "/usai-general-services-administration-artificial-intelligence-google-meta-anthropic-claude-eagleeye-ai-procurement-analytics-federal-agencies/"
  status = 301
